version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: alex
      POSTGRES_PASSWORD: psswd123
      POSTGRES_DB: jsonbase
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data