version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: alex
      POSTGRES_PASSWORD: psswd123566
      POSTGRES_DB: shortener
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data